### PR TITLE
Update Wordle

### PR DESCRIPTION
**Pull request by mlava**
Fix for broken answer source

### CODE REVIEW

**Comment by baibhavbista** [comment]
@mlava can you give more details on this new API you're hitting?
image

**Comment by baibhavbista** [comment]
@mlava 
We talked about this in Slack, but adding here too for future reference:

googled a bit, and some people say that this website works: https://www.nytimes.com/svc/wordle/v2/{YYYY}-{MM}-{DD}.json

For today’s date, for example: https://www.nytimes.com/svc/wordle/v2/2024-06-25.json
`{"id":1791,"solution":"savor","print_date":"2024-06-25","days_since_launch":1102,"editor":"Tracy Bennett"}`
which seems to correspond to the answer when using your extension
image

If possible, we should try to use this API because:
1. is a NYTimes API so will probably be safe
2. will not require you to keep something running in heroku (which you were doing for the herokuapp.com server call above)

**Comment by baibhavbista** [comment]
@mlava 
different behavior now using wordle extension
I think this could be fixed by using `response_data.days_since_launch` instead of `response_data.id`. I’m unsure why there are two different integer counts though
See sample json below:
{"id":1791,"solution":"savor","print_date":"2024-06-25","days_since_launch":1102,"editor":"Tracy Bennett"}
image

**Comment by mlava** [comment]
> @mlava different behavior now using wordle extension I think this could be fixed by using `response_data.days_since_launch` instead of `response_data.id`. I’m unsure why there are two different integer counts though See sample json below: {"id":1791,"solution":"savor","print_date":"2024-06-25","days_since_launch":1102,"editor":"Tracy Bennett"} image

I'm really sorry. Fixed in latest merge

**Pull request merged**
