### PR TITLE
Add Quick Capture with Todoist extension

### PR DESCRIPTION
**Pull request by mlava**
@tonsky 
I believe I've addressed the issues raised in the previous PR.
Cheers!

### CODE REVIEW

**Comment by tonsky** [comment]
This

```
let q = `[:find (pull ?page [:block/children]) :where [?page :block/uid "${uid}"]  ]`;
var results = await window.roamAlphaAPI.q(q);
```

Can be replaced with pull:

```
window.roamAlphaAPI.data.pull("[:block/children]", [":block/uid", uid]);
```

Second issue: fetch status should be checked and reported to user if any request fails? It seems like it will fail silently now

**Comment by mlava** [comment]
@tonsky 
Thank you.
I believe I've corrected those issues. I've also handled default config settings better than before, as well as gibberish in settings when needed.

**Comment by tonsky** [comment]
Looks like you forgot `key` argument in

```
function sendConfigAlert() {
```

And I am still getting these errors if I didn’t configure API token

Screenshot 2022-08-10 at 22 59 10

**Comment by mlava** [comment]
@tonsky 
Sorry, fixed now

**Comment by tonsky** [comment]
Seems to work, thanks!

**Pull request merged**
