### PR TITLE
New Extension - Sheet Music

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Comment by baibhavbista** [comment]
why does this have two similar looking dependencies, @mlava ?
image

**Comment by mlava** [comment]
> why does this have two similar looking dependencies, @mlava ? image

because I'm an idiot...
fixed

**Comment by baibhavbista** [comment]
@mlava  build is failing 😅

**Comment by mlava** [comment]
working on it

**Comment by mlava** [comment]
building now @baibhavbista sorry

**Comment by mlava** [comment]
@baibhavbista this is now ready for review again, using a new library with more functionality.
Cheers :)

**Pull request merged**
