### PR TITLE
New Extension - Algorithms of Thought (AOT)

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Review by baibhavbista — CHANGES_REQUESTED** [review]
Hey @mlava 
Leaving a review for this one

Did not deep dive into the code since it seems that it seemed to be following the logic for the the algorithms

I did get an error that `aot_apc` did not exist when trying to apply "AOT - Alternatives, Possibilities, Choices" - the function seems to not exist

image

**Comment by mlava** [comment]
Hey @baibhavbista 
Thanks, that was a simple error.
Fixed.

**Comment by baibhavbista** [comment]
Hey @mlava , I think you might have forgotten to update the "source_commit"?

**Comment by mlava** [comment]
Sorry!
Sloppy work over here. I blame rushing between clinics to push the new code. ;-)

**Review by baibhavbista — APPROVED** [review]
looks good, thanks for fixing @mlava

**Pull request merged**
