### PR TITLE
Create yesterday & tomorrow nav buttons

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Comment by pablco** [comment]
@mlava It would be cool if there were another two buttons to go to the Next/Previous DNP that exists. What do you think?

**Comment by mlava** [comment]
@pablco
That's interesting. Let me think on it.
It might warrant a separate extension, as this one is intended to create yesterday today and tomorrow buttons that remain fixed rather than changing depending on which page you're on.
Will consider and get back to you.

**Comment by panterarocks49** [comment]
How does this work https://github.com/mlava/yesterday-tomorrow/blob/8912f160d00535cd6ff7a2ee2a79bf18489576b7/extension.js#L163?
I don't see you define that variable anywhere

**Comment by mlava** [comment]
sorry
fixed in e14c6f89e6f7c960b395bae347f97ce22fd54b3c

**Comment by panterarocks49** [comment]
https://github.com/mlava/yesterday-tomorrow/blob/e14c6f89e6f7c960b395bae347f97ce22fd54b3c/extension.js#L137
This will not work right with offline graphs, could you fix to use offline instead of app, you can find the info in `window.roamAlphaAPI.graph.type`
here is an example of using it https://github.com/shodty/roam-breadcrumbs/blob/f500479dfae7ffe56b59e41399508505bc4981c8/extension.js#L119

**Comment by mlava** [comment]
> https://github.com/mlava/yesterday-tomorrow/blob/e14c6f89e6f7c960b395bae347f97ce22fd54b3c/extension.js#L137 This will not work right with offline graphs, could you fix? you can find the info in `window.roamAlphaAPI.graph.type` here is an example of using it https://github.com/shodty/roam-breadcrumbs/blob/f500479dfae7ffe56b59e41399508505bc4981c8/extension.js#L119

thanks for pointing to the fix

I've updated the code and PR

**Comment by panterarocks49** [comment]
no problem, also need to fix here https://github.com/mlava/yesterday-tomorrow/blob/a100ee953ebebc95fdc01de5549d97ad099b29e6/extension.js#L137

**Comment by mlava** [comment]
> no problem, also need to fix here https://github.com/mlava/yesterday-tomorrow/blob/a100ee953ebebc95fdc01de5549d97ad099b29e6/extension.js#L137

Sorry Josh.
Fixed, and checked for other instances and fixed those as well.
Cheers

**Review by panterarocks49 — APPROVED** [review]
Thanks!

**Comment by mlava** [comment]
> https://github.com/mlava/yesterday-tomorrow/blob/e14c6f89e6f7c960b395bae347f97ce22fd54b3c/extension.js#L137 This will not work right with offline graphs, could you fix? you can find the info in `window.roamAlphaAPI.graph.type` here is an example of using it https://github.com/shodty/roam-breadcrumbs/blob/f500479dfae7ffe56b59e41399508505bc4981c8/extension.js#L119

Hey Josh. A user has pointed out that the links open in the browser even when clicked in Electron app. Is there a way to stop that happening? 

I found window.roamAlphaAPI.platform.isDesktop but am not sure how to configure the links after recognising the platform... the console suggests the page is like this:
https://roamresearch.com/?server-port=3333#/app/RoamScripts/page/Ed6sa1Zlf
But how do I form a link to another page?

**Comment by panterarocks49** [comment]
@mlava Sorry! I should have pointed you to this API function https://roamresearch.com/#/app/developer-documentation/page/Svn6FFwsW, this will open the links correctly no matter the platform. You just have to attach a click handler and call the function.

**Comment by mlava** [comment]
@panterarocks49 
No worries, I was aware of that function but sometimes you think you'll do something one way and then close your brain to another.
Thanks for pointing me there. PR with fix incoming.
Cheers!

**Pull request merged**
