### PR TITLE
Update Search+

### PR DESCRIPTION
**Pull request by dive2Pro**

### CODE REVIEW

**Comment by panterarocks49** [comment]
hey just letting you know I have to wait a few more days to review this until I force upgrade everyone to have the new API, should be around middle of next week

**Comment by dive2Pro** [comment]
> hey just letting you know I have to wait a few more days to review this until I force upgrade everyone to have the new API, should be around middle of next week

Thank you for letting me know about this.

I know you guys are busy rolling out something right now too, so don't rush on this one , take your time.

**Comment by panterarocks49** [comment]
Opening a new tab while the search is full screen isn't working for me, the popup doesn't appear until I exit fullscreen, does this happen for you?

**Comment by dive2Pro** [comment]
> Opening a new tab while the search is full screen isn't working for me, the popup doesn't appear until I exit fullscreen, does this happen for you?

Yes. Should be fixed now

**Pull request merged**
