### PR TITLE
Update focus mode to add option to maintain access to search & keyboard shortcut

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Comment by mlava** [comment]
Thanks @panterarocks49 
I tried to remove both of those but had trouble figuring out the code to remove an unnamed eventlistener function. I then tried making them named functions but couldn't unset those either.
I know it's a bit to ask, but can you point to an example I can look at as I spent some time on this and couldn't find...

**Comment by panterarocks49** [comment]
Here I think this should do it

```
var focusModeState;
var hashChange;
var onKeyDown;
export default {
    onload: ({ extensionAPI }) => {
        extensionAPI.settings.panel.create(config);
        window.roamAlphaAPI.ui.commandPalette.addCommand({
            label: "Toggle Focus Mode",
            callback: () => focusModeToggle({ extensionAPI })
        });
        focusModeState = false;

        hashChange = async (e) => {
            monitorPage({ extensionAPI });
        };

        window.addEventListener('hashchange', hashChange);

        onKeyDown = async (e) => {
            if (e.key.toLowerCase() === 'f' && e.shiftKey && e.altKey) {
                keyboardTrigger({ extensionAPI });
            }
        };

        window.addEventListener('keydown', onKeyDown);
    },
    onunload: () => {
        window.roamAlphaAPI.ui.commandPalette.removeCommand({
            label: 'Toggle Focus Mode'
        });
        console.log(hashChange);
        window.removeEventListener('hashchange', hashChange);
        window.removeEventListener('keydown', onKeyDown);
        focusModeOff();
    }
};
```

Certainly not clean code but until I make the change you and David Vargas were talking about in slack this will have to do

**Comment by mlava** [comment]
Thanks @panterarocks49 
I appreciate the code and the quick advice in Slack.
Fixed in https://github.com/mlava/focus-mode/commit/ee7ec0e165221b197a72196c5d9a1a5915c96921
Cheers!

**Review by panterarocks49 — APPROVED** [review]
Thanks! looks good now

**Pull request merged**
