### PR TITLE
Elapsed time calculator

### PR DESCRIPTION
**Pull request by fbgallet**

### CODE REVIEW

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
I get an error when running "Elapsed Time"

image

I am sure that I have smartblocks installed and the command from the store

Also get an error when trying to click this button (the top one, the bottom one works to insert the first timestamp)
image

image

**Comment by fbgallet** [comment]
And what if you run "Elapsed time" from the command palette ?

**Comment by fbgallet** [comment]
Are you running "Elapsed time" while the cursor is in a block with a timestamp ?

**Comment by panterarocks49** [comment]
Yes in this block
image

**Comment by fbgallet** [comment]
Have you set categories uid ?
I can't reproduce the error.
There is some dependencies imported from .`/utils.js` , is it ok ?

**Comment by panterarocks49** [comment]
> Have you set categories uid ?

No, let me try that

> There is some dependencies imported from ./utils.js , is it ok ?

Yes, it doesn't have to be in a single file before compilation, just can't dynamically import anything

**Comment by fbgallet** [comment]
Ok, i've fixed the small issue !

**Review by panterarocks49 — APPROVED** [review]

**Pull request merged**
