### PR TITLE
Add Roam Date UX plugin

### PR DESCRIPTION
**Pull request by Stvad**
via https://github.com/Stvad/roam-date

### CODE REVIEW

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
I can't find the npm package / github repository for `roam-api-wrappers` could you point me to both of those? I need to review that repository as well

There are a couple of different places you need to remove event listeners / hotkeys in `onunload`
https://github.com/Stvad/roam-date/blob/e6fe27525aa5d3dad7398464f62f5f9c1c98efc4/src/navigation.ts#L7
https://github.com/Stvad/roam-date/blob/e6fe27525aa5d3dad7398464f62f5f9c1c98efc4/src/index.ts#L38

The extension.js file size is a lot larger than I'd expect it to be, I think this is because roamjs-components is not being tree shaken correctly due to this import
https://github.com/Stvad/roam-date/blob/e6fe27525aa5d3dad7398464f62f5f9c1c98efc4/src/index.ts#L7
These need to be all separate imports
```
import createBlockObserver from "roamjs-components/dom/createBlockObserver";
...etc
```

Is this config observer used for anything?
https://github.com/Stvad/roam-date/blob/e6fe27525aa5d3dad7398464f62f5f9c1c98efc4/src/index.ts#L40

Your assets in the README should use the full github url, Roam doesn't recognize relative paths

**Comment by panterarocks49** [comment]
Also onunload should remove these calendar buttons
https://github.com/Stvad/roam-date/blob/e6fe27525aa5d3dad7398464f62f5f9c1c98efc4/src/index.ts#L53

**Comment by Stvad** [comment]
Thanks for taking a look!

> Roam API Wrappers

It's https://github.com/Stvad/roam-api-wrappers and package with the same name on npmjs

> removing event listeners, buttons/etc

Is that a hard requirement? I understand that it's nice to do so, but I never bothered to clean up such state in extensions to date, as one can always reload the page.

>The extension.js file size is a lot larger than I'd expect it to be, I think this is because roamjs-components is not being tree shaken correctly due to this import
https://github.com/Stvad/roam-date/blob/e6fe27525aa5d3dad7398464f62f5f9c1c98efc4/src/index.ts#L7
These need to be all separate imports

will check

>Is this config observer used for anything? 

not atm, it's there bc it was part of the template 😛 

> Your assets in the README should use the full github url, Roam doesn't recognize relative paths

👍

**Comment by panterarocks49** [comment]
> Is that a hard requirement? I understand that it's nice to do so, but I never bothered to clean up such state in extensions to date, as one can always reload the page.

Yes that is a hard requirement, both so users can uninstall extensions without reloading the page and so when you update you extension, it updates without reloading the page (and without running two versions at once)

**Comment by Stvad** [comment]
Updated to address the comments :)

**Comment by panterarocks49** [comment]
Thanks! Everything seems good except I still am seeing a size issue, although it is less than before.

See the output of `npx roamjs-scripts build --depot --analyze`
image

lodash is taking up half of the module size (500kb), which is interesting since https://bundlephobia.com/package/lodash@4.17.21 says it should only be ~70kb

I think this is because of this line https://github.com/Stvad/roam-api-wrappers/blob/master/src/data/index.ts#L4 which imports all of lodash
Could you try importing only the functions you need?
I think something like this will work
`import { countBy } from 'lodash';`
but you might need to import from the sublib
`import countBy from 'lodash/collection';`

**Comment by Stvad** [comment]
Will take a look, but those numbers don't make sense to me 🤔. The whole thing built without analyze is ~290kb. buth with analyze it grows to 1.2mb

**Comment by panterarocks49** [comment]
Oh yeah, interesting, didn't realize the extension.js is actually 290kb. No worries if you can't figure it out, 290kb is much better than 1mb!

**Comment by Stvad** [comment]
switching to `lodash-es` helps to get it to 226kb

**Comment by panterarocks49** [comment]
eh, that's not a whole lot, up to you, I read lodash-es has issues

**Comment by Stvad** [comment]
pushed un update for now, may switch back later if encounter those 🤷‍♂️

**Pull request merged**
