### PR TITLE
AI co-pilot (GPT-3)

### PR DESCRIPTION
**Pull request by LayBacc**
Auto-complete your ideas with GPT-3

### CODE REVIEW

**Comment by panterarocks49** [comment]
Do you know if we need to get this approved by OpenAI? Their docs are kind of confusing with regards to whether it needs to be approved if everyone uses their own API keys

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
Can you remove the change to `tweet-extractor.json`?

I don't think you need to be including tailwind css, Roam already provides it, was there part of tailwind we are missing?
https://github.com/LayBacc/roam-ai/blob/80c56e3c6004dceee8b7e05e1db97d41decf6bcc/src/index.css

Are you using this config page for anything?
https://github.com/LayBacc/roam-ai/blob/80c56e3c6004dceee8b7e05e1db97d41decf6bcc/src/index.ts#L87

You need to remove eventListeners in `onunload`
see
https://github.com/LayBacc/roam-ai/blob/80c56e3c6004dceee8b7e05e1db97d41decf6bcc/src/index.ts#L118
https://github.com/LayBacc/roam-ai/blob/80c56e3c6004dceee8b7e05e1db97d41decf6bcc/src/index.ts#L158
You can also return a function from `onload` to do the unloading, which should be easier than pulling those functions out

I'm getting a 401 response, I just made a new OpenAI account, any ideas what might be going wrong? Do I need to get approved or something?
image

**Comment by LayBacc** [comment]
> Do you know if we need to get this approved by OpenAI? Their docs are kind of confusing with regards to whether it needs to be approved if everyone uses their own API keys

let me look into this


and noted the comments 🙏 will fix!

**Comment by Stvad** [comment]
also getting 401, 

details are as 
>         "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://beta.openai.com. Feel free to email support@openai.com if you have any questions.",

(I do have key specified in settings)

**Comment by LayBacc** [comment]
yeah think I found the issues. will carve out some time this weekend to fix

**Comment by LayBacc** [comment]
@panterarocks49 all the requested changes have been made, 
with the exception of removing eventListeners (which I'm trying to get help with in the Roam Slack) 

re: Open AI approval, there is no need for app review for "bring your own key" apps
details here: https://beta.openai.com/docs/usage-guidelines/open-source-bring-your-own-key-applications

**Comment by LayBacc** [comment]
@panterarocks49 all the requested changes have been made. please review

re: Open AI approval, there is no need for app review for "bring your own key" apps
details here: https://beta.openai.com/docs/usage-guidelines/open-source-bring-your-own-key-applications

**Comment by panterarocks49** [comment]
Thanks for clearing that up, I am now getting another error when trying to run

image

I think from here, because I don't have an API key to start
https://github.com/LayBacc/roam-ai/blob/2cf4eccae0a25130ea48e129484326415911ef26/src/index.ts#L87

**Comment by LayBacc** [comment]
that should be a quick fix. will update this PR soon

**Comment by LayBacc** [comment]
@panterarocks49 

added simple error handling that was missing. sorry about that

I just tried the end-to-end flow from the beginning (starting with no key), and it seemed to be working well

https://www.loom.com/share/ab29f216f80042e1b25de7b6f20b48b9

**Comment by panterarocks49** [comment]
I am still getting the same error
image

I think it is from here, because settings is undefined at first
https://github.com/LayBacc/roam-ai/blob/master/src/index.ts#L92

**Comment by LayBacc** [comment]
gotcha. I can repro now (had to uninstall my plugin first)

fixing this asap

**Comment by LayBacc** [comment]
@panterarocks49 the above should be fixed now

turns out I had to first uninstall my plugin, in order to repro

apologies for the back and forth. still getting used to building Roam plugins

**Comment by LayBacc** [comment]
thanks for the feedback @Stvad!

I was debating whether to fix that in this first release. but your feedback confirmed it: lemme fix it this weekend

**Comment by LayBacc** [comment]
added keyboard support! (for arrow keys + enter)

also threw in a bonus mode: ["devil's advocate"](https://twitter.com/Lay_Bacc/status/1573730370054496258) 

https://www.loom.com/share/27fa0c02861545ce97f2733c57dcf960

**Comment by LayBacc** [comment]
@panterarocks49 please let me know if there are any other changes I need to make 🙏

**Comment by panterarocks49** [comment]
Awesome! thanks, it is all working for me now

**Review by panterarocks49 — APPROVED** [review]

**Pull request merged**
