### PR TITLE
Roam Studio

### PR DESCRIPTION
**Pull request by rcvd**
Initial Release

### CODE REVIEW

**Comment by rcvd** [comment]
@panterarocks49: This is the initial release with just one theme. When I add more themes (and fonts), I will quickly exceed the current set size limit of around 4 MB. What would be the recommended workaround for this?

**Comment by rcvd** [comment]
Just added some small bug fixes.

**Comment by panterarocks49** [comment]
> When I add more themes (and fonts), I will quickly exceed the current set size limit of around 4 MB

Who said there was a 4MB limit?

Can you commit the files unminified? Kind of hard to review this way

image

**Comment by rcvd** [comment]
> 


> Who said there was a 4MB limit?
The build process failed. 
Screenshot 2022-08-31 at 06 39 00

> Can you commit the files unminified? Kind of hard to review this way
Updated it with the minified files.

**Comment by panterarocks49** [comment]
Interesting, that is a size limit enforced by roamjs-scripts, roam depot does not have a size limit. I asked David if there is a way to override that.

**Comment by panterarocks49** [comment]
I submitted a PR to your repo fixing the size issue https://github.com/rcvd/RoamStudio/pull/1, you should be able to add the other themes now

**Comment by panterarocks49** [comment]
Aside from the above PR, the only other thing that I noticed that needs to be changed is the dom IDs, they should be prefixed by a name unique to the extension.

https://github.com/rcvd/RoamStudio/blob/master/src/build.js#L410

So instead of `"css-theme"` it should be something like `"roamstudio-css-theme"`, to avoid conflicts with other extensions

**Comment by rcvd** [comment]
Merged PR and updated IDs.

**Comment by panterarocks49** [comment]
Thanks! 

I noticed you changed all ' to " and that had unintended affects on icons-feather, it looks like it broke some of the svgs
https://github.com/rcvd/RoamStudio/blob/master/src/RoamStudio/modules/icons-feather.css#L85

Although it's not used in the PR, so this is still good to merge

**Review by panterarocks49 — APPROVED** [review]

**Comment by panterarocks49** [comment]
@rcvd Shoot, I missed this in the re-review, I am getting an error on unloading RoamStudio because some of the IDs were not updated, here https://github.com/rcvd/RoamStudio/blob/81ca3433521b8f9f94623030070616bc7cc7a6fa/src/build.js#L420
Could you update those IDs sooner than later in a new PR?

**Comment by rcvd** [comment]
Will do, thanks for input.

**Pull request merged**
