### PR TITLE
Fix YouTube links extension

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Comment by panterarocks49** [comment]
Hey what are some examples of broken youtube links? if it's just missing `www` like in your example then we can fix that on our end so you don't have to add it (we already do a bunch of processing on yt links)

**Comment by mlava** [comment]
I get a lot of imports from Readwise that are missing the www. They come
from annotate.tv which I think sends them to Readwise without the www
I think that's my main source of irritation :-D

**Comment by panterarocks49** [comment]
Ok, I'm going to try to fix this in our code and hold off on this extension

**Comment by mlava** [comment]
No worries

**Comment by panterarocks49** [comment]
Released a fix for this today

**Comment by mlava** [comment]
Awesome, thanks!

**Pull request closed without merging**
