### PR TITLE
add Reference path

### PR DESCRIPTION
**Pull request by paulovieira**

### CODE REVIEW

**Comment by 8bitgentleman** [comment]
@paulovieira  are you in contact with the original author and have they agreed to pass pass on proceeds? Been trying to contact him myself for my own fork but haven't heard

**Comment by paulovieira** [comment]
> @paulovieira are you in contact with the original author and have they agreed to pass pass on proceeds? Been trying to contact him myself for my own fork but haven't heard

Hello Matt! No, I'm not in contact with Azlen Elza. But if he is not ok about this extension, I'm happy to remove it or transfer the code to his github account (or give him credit in the author field). The readme already gives credit to the original authors since the initial commit.

Looking at his twitter account (https://twitter.com/azlenelza) I'd say he is some kind of genius who has more important things to think about.

Having said this, the code has been completely rewritten with performance in mind:
- the [arrive.js](https://github.com/uzairfarooq/arrive) library was removed (huge waste there)
- the usage of MutationObserver is optimized to avoid unnecessary work
- the `style.textContent = baseStyle + ...` hack was replaced with css custom properties (much simpler now, and aligns well with the `extension.css` file)

I think the important thing is to have this extension readily available in roam depot.

**Comment by 8bitgentleman** [comment]
I will of course defer to the roam team's decision here :)
in the meantime a couple of suggestions 

- customizable line thickness 
- keyboard toggle (I believe the original used `ctrl` + `i`
- different root vars for bullet scale on open/closed

**Comment by panterarocks49** [comment]
Hey @paulovieira sorry for the long wait on this one. I had been debating whether or not to allow it since Azlen came up with it. Given that you are ok transferring if he wishes later I think we can approve this one

Also, there is an issue with your stripe account, for this extension and for your other one. I can't find it in our dashboard. I think you need to go in and finish filling it out (or maybe you pasted in the wrong acct number), all information needs to be filled out in order for us to be able to transfer money to you. Please fix this sooner rather than later because the first payouts for last month went out today for other developers
Thank you

**Comment by paulovieira** [comment]
Hello Joshua! Thanks for the update.

> Hey @paulovieira sorry for the long wait on this one. I had been debating whether or not to 
> allow it since Azlen came up with it. Given that you are ok transferring if he wishes later I think 
> we can approve this one

Great, I think this is a good compromise!

As I said before, my interest is to have this nice extension available in roam depot as soon as possible, and but also implemented with performance in mind (which the original code was not, in my opinion). 

When you have 10+ extensions using bloated code, it's easy to ruin the experience of using roam. And that will be a very real scenario as the number of extensions grows.

Meanwhile I've also posted a message about this issue in the [original Azlen's gist](https://gist.github.com/azlen/cc8d543f0e46e17d978e705650df0e9e?permalink_comment_id=4266524#gistcomment-4266524), and sent him an email with the same message (email address found at his website - https://azlen.me/intro/). I suggest that we wait a few more days to see if he says something.

Screenshot_2022-08-14_12-49-07


> Also, there is an issue with your stripe account, for this extension and for your other one. I can't find it in 
> our dashboard. I think you need to go in and finish filling it out (or maybe you pasted in the wrong acct number), 
> all information needs to be filled out in order for us to be able to transfer money to you. Please fix this sooner 
> rather than later because the first payouts for last month went out today for other developers Thank you

Thanks letting me know. I'll try to fix it, but no problem if I can't fix it on time. It's not an important thing for me. In fact I prefer to not have any stripe account at all in the reference path plugin, to clarify that I don't have any money intentions.

**Comment by paulovieira** [comment]
> Also, there is an issue with your stripe account, for this extension and for your other one. I can't find it in our dashboard. 
> I think you need to go in and finish filling it out (or maybe you pasted in the wrong acct number), all information needs 
> to be filled out in order for us to be able to transfer money to you. 

An update about this second point: I finally clicked the button to finish the stripe account associated to my roam user, and it seems that the type of stripe payments being used for extensions are [Instant payouts](https://stripe.com/docs/payouts/instant-payouts). However these payouts seem to be available only in a limited number of countries.

For Portugal, in particular, (which is where I am) it is not supported. I get this error when using the "Debit card" option (and the "Bank account" option doesn't support any banks in Portugal).

Screenshot_2022-08-14_23-38-32

So unless there is some alternative (like using other type of payout in Stripe, or some other service like paypal), I think this should be clarified in the [roam depot documentation](https://roamresearch.com/#/app/developer-documentation/page/5BB8h4I7b), in the Introduction block.

For me this is not a problem, but other people might be upset.

**Comment by panterarocks49** [comment]
@paulovieira sorry, I was not aware there was an issue with Portugal. Stripe team told me every country on this list https://stripe.com/docs/connect/cross-border-payouts should be supported (Portugal is included). I am also not sure how to disable instant payouts (I never enabled it) to fix your issue.
I will clarify the documentation that before creating an extension you should try to sign up and become verified through stripe. Stripe is our only option right now for payouts

If you are not able to complete the stripe verification, could you remove the stripe accounts from your extensions? It will help me with distributing funds

**Comment by panterarocks49** [comment]
For the code review:
I am getting bugs with creating a new block, deleting blocks, indenting and unindenting. The reference path does not update

I end up in situations like this where the reference path is in the location of where the block used to be

image

Could you fix?

Also, there are a number of `console.log`s happening, could you remove / switch to using your `log` function so they only appear in debug?

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
see above comment

**Comment by panterarocks49** [comment]
Did you mean to close this? looks like it auto closed when you force pushed your branch to our main branch

**Comment by paulovieira** [comment]
Sorry, I didn't meant to close it. I guess I messed something with git/github while trying to make a new commit relative to my other plugin (show-favicon), to remove the stripe account.

Anyway, this one (reference path) is not yet ready for review, sorry again for the confusion. There are a bunch of updates in my repo that solve those issues, but I haven't yet updated the commit reference in roam-depot, so you I guess you were reviewing outdated code. I'm very close though. Please ignore this PR/extension for now, give me a few more days.

By the way, meanwhile I got a response from Azlen Ezla saying it was ok to go ahead with having this extension in roam depot.

**Pull request merged**
