### PR TITLE
Bug Fix: Unsplash missing css

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Comment by panterarocks49** [comment]
this doesn't have iztoast so the css changes aren't needed without that, and this shouldn't have been approved with the @omiu/dialog-extention dependency

**Comment by mlava** [comment]
I thought I had uploaded new js with izitoast and removing omiu. Will do that this morning. I had updated to remove omiu after your advice to use izitoast...

**Comment by mlava** [comment]
Hi Josh @panterarocks49 sorry for the sloppy PR.
I've now uploaded the package.json and src/index.js that remove the omiu dependency and replace with izitoast.
Thanks and sorry again.

**Comment by panterarocks49** [comment]
@mlava  No worries, thanks for fixing

**Pull request merged**
