### PR TITLE
Create Shortcode Embed extension

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
Could you add something to the readme telling people they can use it via the command palette? I had to look at the code to figure that out

Other than that looks good

**Comment by panterarocks49** [comment]
Maybe also change it to say "Paste Embed from clipboard", instead of just "Embed from clipboard"

**Comment by mlava** [comment]
Thanks @panterarocks49 
Both changes made and pushed to https://github.com/mlava/shortcode-embeds/commit/920a1784afba57857f6ffe8586180b65517e8e6a

**Review by panterarocks49 — APPROVED** [review]
Thanks!

**Pull request merged**
