### PR TITLE
add ryanguill/roam-depot-export-formatter

### PR DESCRIPTION
**Pull request by ryanguill**

### CODE REVIEW

**Comment by panterarocks49** [comment]
Your README assets need to be direct http links otherwise they won't show up right in Roam

**Comment by ryanguill** [comment]
Ok good to know - any preference on where those are hosted?

**Comment by panterarocks49** [comment]
No, can be github or Roam or wherever

**Comment by ryanguill** [comment]
Images updated! Thanks @panterarocks49, let me know if theres anything else I need to change or tweak.

**Review by panterarocks49 — APPROVED** [review]
Thanks!

**Comment by ryanguill** [comment]
Thank you! Awesome to see it in roam already, so exciting

But I am noticing that I see "Error Loading Readme" - is that something I have broken on my end? Any way for me to debug that further? It doesn't seem to just be images, but the whole readme?

**Pull request merged**
