### PR TITLE
New Extension: Autopin

### PR DESCRIPTION
**Pull request by sweenzor**
Thank you.

### CODE REVIEW

**Comment by panterarocks49** [comment]
Hi, it looks like you forgot to add the `.json` extension to the `autopin` file. Could you update the file name? thanks

**Comment by sweenzor** [comment]
Hey @panterarocks49, am I doing something obviously dumb to cause the tests to fail?

**Comment by panterarocks49** [comment]
Our json parser is not very smart, it doesn't like the extra comma on your last key value pair I think

image

**Comment by sweenzor** [comment]
> Our json parser is not very smart, it doesn't like the extra comma on your last key value pair I think
> 
> image
> 
> image

oh duh. thanks!

**Pull request merged**
