### PR TITLE
Add Weathercards

### PR DESCRIPTION
**Pull request by mlava**
updated to remove reliance on dayjs library

### CODE REVIEW

**Comment by panterarocks49** [comment]
Which api do I need to subscribe to?

image

**Comment by mlava** [comment]
Current Weather Data

Sorry, will update the readme

**Comment by panterarocks49** [comment]
I am having similar api issues here

Here is one of my API keys if you could try with it `20bcf78d7f96c79191342d2a198e3ac0`

Can you confirm I have the right plan?
image

**Comment by mlava** [comment]
That looks the same as mine:

image

I tried with your API key and get the same error... maybe it takes some time to work?

**Comment by mlava** [comment]
Is your api key showing as active:

image

**Comment by panterarocks49** [comment]
yeah it shows as active

I'll put this one on hold for now and try again later or tomorrow

**Comment by panterarocks49** [comment]
Tried again, I still get the same error, won't let that hold this up though, going to merge and we'll see if other people can get it to work

**Review by panterarocks49 — APPROVED** [review]

**Pull request merged**
