### PR TITLE
Add Left Expander Extension

### PR DESCRIPTION
**Pull request by oschmid**
See github.com/oschmid/left-expander

### CODE REVIEW

**Comment by oschmid** [comment]
Ah based on some of the other published extensions it looks like it will show the video.

**Comment by panterarocks49** [comment]
Hey could you remove the element in `onunload`?
Looks like you already have the code for it here https://github.com/oschmid/roam-left-expander/blob/5a67dc1c810cae671bc07933dada74b1f466742c/extension.js#L10

**Comment by oschmid** [comment]
Good suggestion! Fixed

**Comment by panterarocks49** [comment]
Hey @oschmid there is an issue with your stripe account, either you have not finished filling it out or you pasted in the incorrect number. Could you please check that the account is fully filled out and the number is correct. We cannot transfer money to you until this is complete.

**Comment by oschmid** [comment]
Thanks for letting me know. The "acct_" number looks correct and I filled out some details that appeared to be missing. Does it work now?

**Comment by panterarocks49** [comment]
Sorry for the late response on this, I still can't find it. `acct_1LOocACFS9HLlkP7` is the account we have for you
Are you sure you signed up for stripe through Roam?
The account is visible from this screen
image

**Comment by oschmid** [comment]
Ah I missed that instruction and setup my stripe account outside of Roam. I got a new value from within Roam and opened https://github.com/Roam-Research/roam-depot/pull/133 Thanks for your help!

**Pull request merged**
