### PR TITLE
New extension: Unread Badge

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
https://github.com/mlava/unread-badge/blob/ba11d1efe6180125fb09bd28a6f3f22a1cdf6806/extension.js#L165
Need to clear this interval onunload, also store it in a local var instead of the window object to avoid conflicts with other extensions

**Comment by panterarocks49** [comment]
How do I process an unread?

**Comment by panterarocks49** [comment]
Installing was a bit of a weird process, I first got an alert to add a tag, then I added the tag and nothing happened. I think it should be reactive to the settings, I had to reload the page to get it to show the tag

**Comment by mlava** [comment]
Thanks Josh. Will get back to finessing this one a bit more. Cheers!

**Comment by panterarocks49** [comment]
> PS @panterarocks49 Does the API allow set/unset of starred/shortcut status for a page? I can't seem to find it in docs...

I thought it did, but it looks like it doesn't

**Comment by mlava** [comment]
Never mind. Any plans for that to change, or should I go about it the hard
way?  😁

**Comment by panterarocks49** [comment]
I can add it

**Comment by panterarocks49** [comment]
Will try to add it this weekend

**Comment by mlava** [comment]
awesome, thanks!

**Comment by mlava** [comment]
Hey @panterarocks49 
I think I've finessed the setup process and sorted the interval set and unset as requested.
Without access to an API function to check for a Shortcut, it will just pop up and alert reminding the user to create on if they are using shortcut mode. If they are using Menu item mode the div will be created and destroyed.
Cheers!

**Comment by 8bitgentleman** [comment]
Is there any way to make this a true circle or at least a horizontal oval? This squished vertical oval looks kind of strange
image

**Comment by mlava** [comment]
@8bitgentleman will work on it, cheers
Is it working properly otherwise?

**Comment by 8bitgentleman** [comment]
Just installed it today and seems to work well! I'll play with it for a few days and let you know if there are any issues

**Comment by panterarocks49** [comment]
@mlava Thanks for updating, I still haven't had a chance to add star page so I am going to merge this

**Review by panterarocks49 — APPROVED** [review]

**Comment by mlava** [comment]
Thanks @panterarocks49 
Do you think you will add starred pages at some point?
I'll revise this once that's available.
Cheers!

**Pull request merged**
