### PR TITLE
Update Oblique Strategies

### PR DESCRIPTION
**Pull request by mlava**
fix for css collisions with other izitoast extensions

### CODE REVIEW

**Comment by baibhavbista** [comment]
@mlava the extension does not work for me in this version
Maybe you deleted more CSS than you should've?

**Review by baibhavbista — CHANGES_REQUESTED** [review]
@mlava  the extension does not work for me in this version
Maybe you deleted more CSS than you should've?

**Comment by mlava** [comment]
Sorry, fixed now. @baibhavbista

**Comment by baibhavbista** [comment]
lgtm, will release now

**Pull request merged**
