### PR TITLE
Google: Version 2022-10-03-03-35

### PR DESCRIPTION
**Pull request by dvargas92495**

### CODE REVIEW

**Comment by panterarocks49** [comment]
Any update on this? I can try again if you weren't able to reproduce

**Comment by dvargas92495** [comment]
gah sorry - I had iterated on this when you first posted the issue but the deploy failed - fix should now be live

**Comment by panterarocks49** [comment]
Adding a calendar event I get this error

image

image

When trying to create an event from this block
image


Importing my calendar for today results in an error
image

This is my calendar I'm trying to import
image

**Comment by dvargas92495** [comment]
The create bug should be fixed

The import issue should now output a better error message - your calendar id can be found in your calendar settings under the "Integrate your calendar" section. It's usually your email address

**Review by panterarocks49 — APPROVED** [review]

**Pull request merged**
