### PR TITLE
Add initial release of Todoist Task Management extension

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Comment by panterarocks49** [comment]
Hey could you add some description to the README? How is this different than your other TODOist quick capture?

**Comment by mlava** [comment]
Sorry @panterarocks49 I forgot to do the README!

https://github.com/mlava/todoist-task-management/commit/be32c1b05926586103fcceb5f7ad45ace91bfb07
Fixed with some description, a video and TODO list. Cheers!

**Comment by panterarocks49** [comment]
Also need to remove the eventlistener here https://github.com/mlava/todoist-task-management/blob/be32c1b05926586103fcceb5f7ad45ace91bfb07/extension.js#L54

**Comment by panterarocks49** [comment]
Not sure why you need to wait for dom content to be loaded https://github.com/mlava/todoist-task-management/blob/be32c1b05926586103fcceb5f7ad45ace91bfb07/extension.js#L58

**Comment by panterarocks49** [comment]
Should also disconnect the observer here https://github.com/mlava/todoist-task-management/blob/be32c1b05926586103fcceb5f7ad45ace91bfb07/extension.js#L81

**Comment by panterarocks49** [comment]
I'm confused by starting the observer here https://github.com/mlava/todoist-task-management/blob/be32c1b05926586103fcceb5f7ad45ace91bfb07/extension.js#L135

When it has already been started in `onload`, is this necessary?

**Comment by panterarocks49** [comment]
Curious if you have seen roamist https://github.com/Roam-Research/roam-depot/pull/57 and whether this does something different? (not blocking I think it's good to have different implementations for different purposes)

**Comment by mlava** [comment]
Thanks @panterarocks49 
All fixed. Thanks for checking.
I hadn't seen Roamist yet, although I note it was inspired by my Universal Quick Capture SmartBlock  👍 
I still hope this one can go up anyway?

**Comment by panterarocks49** [comment]
yeah not blocking this one, just wanted to point it out

**Comment by mlava** [comment]
maybe we'll end up collaborating?

**Review by panterarocks49 — APPROVED** [review]

**Pull request merged**
