### PR TITLE
new extension: power theme manager

### PR DESCRIPTION
**Pull request by dragonforce2010**

### CODE REVIEW

**Comment by dragonforce2010** [comment]
can anyone review this pr?

**Comment by baibhavbista** [comment]
Hey @dragonforce2010, 

I talked about this a bunch in [my review](https://github.com/Roam-Research/roam-depot/pull/593#issuecomment-1523125083) on PR #593 too

What I think you should do is encapsulate all the themes in one single single extension

**Comment by dragonforce2010** [comment]
will close this pr since I have merged all the roam theme extensions into one extension.

**Comment by baibhavbista** [comment]
great!
For future reference, the PR for the single extension is #593

**Pull request closed without merging**
