### PR TITLE
Bug fixes Workspaces & New feature: autosave & New feature: custom CSS & Enhancement: save and restore filters for main page and sidebar

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Comment by mlava** [comment]
Add new feature:
autosave workspaces so you never lose your place

**Comment by panterarocks49** [comment]
Could you remove this pull watch in onunload?
https://github.com/mlava/workspaces/compare/ab21e29dcfdf5c8fe063eaffdde5d69fe48d4d24..46cd1cd470d7e45d591da5eb39545960144264e5#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R171

**Comment by mlava** [comment]
dammit, sorry @panterarocks49 
done

Also had to tweak some of the settings around kb shortcuts

**Comment by panterarocks49** [comment]
Since you redefined `function a` here, it's not actually the same as the other `function a` and this won't work to remove it correctly, you need to define `function a` at the top level (probably named something else) and reuse that single definition
https://github.com/mlava/workspaces/compare/ab21e29dcfdf5c8fe063eaffdde5d69fe48d4d24..e9f3af458a9df03f605c9cefb3f08caebcfcc7d4#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R125

**Comment by mlava** [comment]
Thanks Josh. I thought I might get stuck on this one.
I am not actually sure how to do what you're proposing. Could you please give me an example? Or is this sort of what you're suggesting:

```
var namedFunction;

export default {
    onload: ({ extensionAPI }) => {

    },
    onunload: () => {
        window.roamAlphaAPI.data.removePullWatch(
            "[:block/children :block/uid :block/string {:block/children ...}]",
            `[:block/uid "${pullBlock}"]`,
            namedFunction(before, after) { checkWorkspaces(); getKBShortcuts(); });
    }
}

async function checkFirstRun() {
    
    await window.roamAlphaAPI.data.removePullWatch(
        "[:block/children :block/uid :block/string {:block/children ...}]",
        `[:block/uid "${pullBlock}"]`,
        namedFunction(before, after) {
            checkWorkspaces(before, after);
            getKBShortcuts();
        });
    await window.roamAlphaAPI.data.addPullWatch(
        "[:block/children :block/uid :block/string {:block/children ...}]",
        `[:block/uid "${pullBlock}"]`,
        namedFunction(before, after) {
            checkWorkspaces(before, after);
            getKBShortcuts();
        });
}

**Comment by panterarocks49** [comment]
I think you just need to do this at the top level
```
function namedFunction(before, after) {checkWorkspaces(before, after); getKBShortcuts();}
```

**Comment by panterarocks49** [comment]
and then add / remove pull watch is this
```
await window.roamAlphaAPI.data.addPullWatch(
        "[:block/children :block/uid :block/string {:block/children ...}]",
        `[:block/uid "${pullBlock}"]`,
        namedFunction);
```

**Comment by mlava** [comment]
Thank you. It was simple after all.
PR updated.

**Review by panterarocks49 — APPROVED** [review]

**Pull request merged**
