### PR TITLE
new extension: website title parser

### PR DESCRIPTION
**Pull request by dragonforce2010**

### CODE REVIEW

**Comment by panterarocks49** [comment]
You need a build.sh file that contains shell commands to build your extension instead of committing the extension.js file. Also it looks like your extension.css is leftover from the example repository

**Comment by dragonforce2010** [comment]
> You need a build.sh file that contains shell commands to build your extension instead of committing the extension.js file. Also it looks like your extension.css is leftover from the example repository

gotcha, I will fix it, thanks

**Comment by panterarocks49** [comment]
Is it intentional to send all of the paste data to your server? 
For example, if I paste "hello world  https://roamresearch.com test" then the entire string gets sent to your server, not just the url, this is also a bug, since it doesn't convert the url included

**Comment by dragonforce2010** [comment]
> 

it's not intentional to send all the paste data to the server, it's a bug, let me fix it.

**Pull request merged**
