### PR TITLE
Universal Selector

### PR DESCRIPTION
**Pull request by fbgallet**
Didn't appear in pull request list anymore, I suppose I've made a mistake in pushing last update this night! But it was pushed here 14 days ago.

### CODE REVIEW

**Comment by panterarocks49** [comment]
I think the PRs auto close if the files changed = 0, kind of annoying but not sure how to disable that

**Comment by panterarocks49** [comment]
I'm not sure what is going wrong but the extension.js is not being output to the top level directory, it is output inside of the `build` folder. 
Since you're not actually using any external deps I'd recommend just copy pasting index.js to the top level and renaming to extension.js

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
In addition to the comment above, I was not able to get this to work, I started by trying the buttons, and then tried the command palette command

image

Here are the errors I get
image

I have smartblocks installed

image

Any ideas?

**Comment by fbgallet** [comment]
You need to install the corrsponding SmartBlock from the Sb store

**Comment by panterarocks49** [comment]
I think you have to remove build.sh as well, the build fails if not

**Comment by panterarocks49** [comment]
> You need to install the corrsponding SmartBlock from the Sb store

Oh right sorry, did not read the README in full

Is there a reason to split it up like that? can you not register the smartblock from the code easily?

**Comment by fbgallet** [comment]
I can register Smartblocks commands but not workflows. By the way, some users were already using the Smartblock and are waiting for the update since Smartblock extension rules changes, and I will release a version (in one or two weeks) that will works without Sb.

**Review by panterarocks49 — APPROVED** [review]

**Pull request merged**
