### PR TITLE
Add Document Export to DOCX and PDF

### PR DESCRIPTION
**Pull request by mlava**

### CODE REVIEW

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
https://github.com/mlava/export-document/blob/1a9978c2e4bef593e809eae0e9f66621b92b7159/extension.js#L157
We don't allow dynamically loading scripts in Roam Depot

Instead you'll have to set up the repo with npm / yarn / webpack

[autotag](https://github.com/panterarocks49/autotag) is a good example of this, I have a (rather long) video on porting the library as well https://roamresearch.com/#/app/developer-documentation/page/3nmEK2Z3M

**Comment by panterarocks49** [comment]
You should also reuse our export of Filesaver.js as well, see https://roamresearch.com/#/app/developer-documentation/page/QBK1-Gh3J

**Comment by mlava** [comment]
@panterarocks49 
I have tried to follow your video and package this all up using webpack.
I think it works, although first time doing this so forgive me ;-)
Let me know if this is what is needed for this kind of extension file. Cheers!

**Comment by mlava** [comment]
@panterarocks49 
All the required build files should now be present.
I hope this is the correct format.
Cheers!

**Comment by panterarocks49** [comment]
@mlava is there a reason you didn't use https://github.com/privateOmega/html-to-docx? it looks more reputable (and up to date) than the library you are using. Although not technically a blocker, it might hold up this PR until I have time to do an in depth review of the library you are using

**Comment by mlava** [comment]
@panterarocks49 
I'm pretty sure I tried but couldn't get it to work. Will go back and try again 👍

**Comment by mlava** [comment]
@panterarocks49 I can't get that package to build in webpack. I've posted an issue on their github but received no response. It's an issue with polyfills but I just can't get it done. I asked David Vargas for help but I don't think he's had the chance.

Is there a chance you could look at this extension with this package instead?

**Comment by mlava** [comment]
@panterarocks49 
I finally got this to build with the suggested docx package. Sorry, it's taken a lot of trial and error to get it to build in webpack.
It's now ready for review.
Cheers!

**Comment by mlava** [comment]
@panterarocks49 have you had a chance to look at this yet? Just wondering if I need to make more changes? Cheers

**Comment by panterarocks49** [comment]
Sorry I missed that this had been updated the last time I reviewed extensions, I will take a look the next time I get a chance, but likely won't be for a week and a half because we have a team onsite sprint next week

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
Marked is not defined here https://github.com/mlava/export-document/blob/5ec6b9bd8c6abba906a44de0485b9c0659bc0642/src/index.js#L156

We provide marked so instead of including it in your npm modules you can just add this to the function where you use it
`let marked = await RoamLazy.Marked()`

**Review by panterarocks49 — APPROVED** [review]

**Pull request merged**
