### PR TITLE
Color highlighter

### PR DESCRIPTION
**Pull request by fbgallet**

### CODE REVIEW

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
Did you mean to remove Bionic text in this PR? If you are removing Bionic text please do so in a separate PR

**Comment by fbgallet** [comment]
I'm not removing Bionic text from the main branch, but from this branch. Bionic text is on the main branch, and now I create a new branch for each new extension. But I'm probably doing it wrong, since what is already in the main branch is duplicated unnecessarily.

**Comment by panterarocks49** [comment]
If you remove it from your branch, it will remove it from our branch when you merge it, take a look at the changed files in the PR. I think you just have to update your branch to our main branch, then apply your changes (the new extension). In the github UI I have something to update my fork, not sure if that applies to branches though
image

**Comment by fbgallet** [comment]
Ok, so I updated the branch, but that doesn't recover bionic-text.json. So I copied it in this branch. And I suppose that I need to copy all my .json in all my branches ?

**Comment by panterarocks49** [comment]
yeah, if it's missing it, the "files changed" should only include the current extension being changed

**Review by panterarocks49 — CHANGES_REQUESTED** [review]
https://github.com/fbgallet/roam-extension-color-highlighter/blob/d7917872568829e1968a688f9ca67c4326e2c60c/build.sh#L2
This needs to be `roamjs-scripts build --depot`

**Comment by panterarocks49** [comment]
> Select some part of your text inside a block, add Highight or bold with native Roam hotkeys (Ctrl or Cmd + h for highlight, Ctrl or Cmd + b for bold), then press a letter corresponding to the first letter of the color (without pressing Ctrl-Cmd anymore), e.g. 'g' for green. If you press Shift when pressing the color first letter, the color will be more vivid and the text color in the highlight will be white instead of black.

I can't get this to work, I typed some text, highlighted it, pressed `cmd-h`, let go of held keys, pressed `f`, and it just overwrote my text. Am I missing something?
I can use it through the command palette commands

**Comment by fbgallet** [comment]
Oh, I'm working on Windows, I've not tested on Mac. I suppose that I need to add a test on 'event.metaKey' and not only "event.ctrlKey" !

**Comment by fbgallet** [comment]
I've pushed an update, I hope it will properly listen to 'cmd+h' on Mac.

**Review by panterarocks49 — APPROVED** [review]
Awesome, works now, thanks!

**Pull request merged**
