### PR TITLE
Tweet Extract

### PR DESCRIPTION
**Pull request by 8bitgentleman**
Roam Research Plugin to extract saved tweet text and metadata into your graph. 

  To set up the format of your extracted tweet a simple template system is included, found in the Roam Depot plugin settings panel. For each supported `{OPTION}` the variable will be replaced with the extracted tweet information.

  Options available to the template are `{TWEET}`, `{URL}`, `{AUTHOR_NAME}`, `{AUTHOR_URL}`, `{DATE}`, `{NEWLINE}`.  A default temlpate is included.

  `[[>]] {TWEET} {NEWLINE} [🐦]({URL}) by {AUTHOR_NAME} on [[{DATE}]]`
  

  To trigger the tweet extraction you have two options: Right click plugin or keyboard shortcut

  To trigger via a keyboard shortcut click into the block and hit a `CTRL` + `SHIFT` + `E`. (will be remapable once that is exposed via the extension API)

## Example 
  </img>

### CODE REVIEW

**Comment by baibhavbista** [comment]
@8bitgentleman pretty cool plugin

Going through the code, I saw that you have react and chrono-node as dependencies (https://github.com/8bitgentleman/roam-depot-tweet-extract/blob/4cba6978305ceb6dd59c8b2f13a4646e35327832/webpack.config.js#L3). Where are you using them?

**Comment by 8bitgentleman** [comment]
Ah that's what I get for copy/paste. Removed those in the lasted commit. Thanks @baibhavbista !

**Comment by baibhavbista** [comment]
Hmm @8bitgentleman, if you're not using any dependencies, is the build.sh script still necessary?
It's not much of an issue, but if it's not required, why make it more complicated than needed?

**Comment by baibhavbista** [comment]
Oh okay @8bitgentleman . You're right, i forgot about fetch-jsonp

**Comment by baibhavbista** [comment]
lgtm.. will merge now

**Pull request merged**
