### PR TITLE
Custom Mobile Buttons

### PR DESCRIPTION
**Pull request by 8bitgentleman**
An extension to add custom buttons to the bottom bar on mobile. First time using a reactComponent in the settings panel, not sure about the styling.
Also if there is a simple way to toggle between formatting (eg bold on/off) I haven't figured it out

### CODE REVIEW

**Comment by panterarocks49** [comment]
> Also if there is a simple way to toggle between formatting (eg bold on/off) I haven't figured it out

There isn't

**Comment by panterarocks49** [comment]
Small thing I noticed, sometimes I get [object object] displayed here, but doesn't seem to break anything

image

**Comment by panterarocks49** [comment]
Other than that, it looks good to me, lmk if you want me to merge it with that bug or fix it

**Comment by 8bitgentleman** [comment]
Thanks for the review! I have an idea for a better solution that may get rid of [object object], I'll look into it this week

**Comment by panterarocks49** [comment]
Do you want me to merge it in the meantime? seems like a small enough bug that it won't effect users

**Comment by 8bitgentleman** [comment]
Sure you can go ahead and merge

**Pull request merged**
