### PR TITLE
New extension: Learn English in RR

### PR DESCRIPTION
**Pull request by qcrao**

### CODE REVIEW

**Comment by qcrao** [comment]
@baibhavbista Hi, Can you help me review this new extension?🤩

**Comment by panterarocks49** [comment]
Hi @qcrao, cool extension!

Here is my first pass at review

`@anthropic-ai/sdk` and `lamejs` appear to not be used, could you remove them from deps list?

You need to clean up the observer onunload https://github.com/qcrao/learn-english-in-RR/blob/a2ec7338d7ea3411719da46c41a17ad025856ee6/src/index.js#L61

You need to remove block context menu cmd onunload https://github.com/qcrao/learn-english-in-RR/blob/a2ec7338d7ea3411719da46c41a17ad025856ee6/src/utils/commands.js#L63

I used `npx roamjs-scripts build --depot --analyze` to analyze the bundle and it looks like font awesome is taking up a huge amount of space and you are only using it for a single icon, could you remove this?

image

I would suggest just using blueprint's icon https://blueprintjs.com/docs/versions/3/#icons for volume up, it looks about the same but matches RR's theme

**Comment by qcrao** [comment]
> Hi @qcrao, cool extension!
> 
> Here is my first pass at review
> 
> `@anthropic-ai/sdk` and `lamejs` appear to not be used, could you remove them from deps list?
> 
> You need to clean up the observer onunload https://github.com/qcrao/learn-english-in-RR/blob/a2ec7338d7ea3411719da46c41a17ad025856ee6/src/index.js#L61
> 
> You need to remove block context menu cmd onunload https://github.com/qcrao/learn-english-in-RR/blob/a2ec7338d7ea3411719da46c41a17ad025856ee6/src/utils/commands.js#L63
> 
> I used `npx roamjs-scripts build --depot --analyze` to analyze the bundle and it looks like font awesome is taking up a huge amount of space and you are only using it for a single icon, could you remove this?
> 
> image
> 
> I would suggest just using blueprint's icon https://blueprintjs.com/docs/versions/3/#icons for volume up, it looks about the same but matches RR's theme

Thanks you very much for your review. I have addressed all the issues and updated the version.

**Comment by panterarocks49** [comment]
Thanks! looks good now

**Pull request merged**
